// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emneomnbjzfxtwnytqmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbmVvbW5ianpmeHR3bnl0cW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTk4MzgsImV4cCI6MjA2NTU5NTgzOH0.TXCuNDyrbiitPxH7EW0bjPktWbuSZETtiMCvRgA-zUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);